apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jupyterhub
  namespace: default
spec:
  interval: 5m
  url: https://jupyterhub.github.io/helm-chart/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: jupyterhub
      version: '1.2.x'
      sourceRef:
        kind: HelmRepository
        name: jupyterhub
        namespace: default
      interval: 1m
  values:
    replicaCount: 1
